on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get source branch name
        if: steps.pr-merged.outputs.merged == 'true'
        id: get-branch-name
        run: echo "::set-output name=branch::${{ github.event.pull_request.head.ref }}"

      - name: Tag main branch with release branch name
        if: steps.pr-merged.outputs.merged == 'true' && startsWith(github.event.pull_request.head.ref, 'release/')
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.pull_request.head.ref }}
          target: main
