on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get source branch nam
        run: echo "${ github.event.pull_request.head.ref }"
