on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release branch name
        id: get_release_branch_name
        run: echo "{release_branch}={$(echo ${GITHUB_REF#refs/heads/})}" >> $GITHUB_OUTPUT
      - name: Tag main branch with release tag
        run: |
          echo ${{ steps.get_release_branch_name.outputs.release_branch }}
          git tag -a ${{ steps.get_release_branch_name.outputs.release_branch }} -m "Release ${{ steps.get_release_branch_name.outputs.release_branch }}"
          git push origin --tags
