name: Tag Release on Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - release
jobs:
  tag_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get the version number
        id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Create release tag
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = "${{ steps.get_version.outputs.version }}";
            const context = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `v${version}`,
              ref: 'main',
              message: `Release v${version}`
            };
            github.git.createRef(context);
